# Generated by Django 3.0.7 on 2020-06-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=30)),
                ('name_last', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeamStint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('b_ab', models.PositiveIntegerField()),
                ('b_pa', models.PositiveIntegerField()),
                ('b_hits', models.PositiveIntegerField()),
                ('b_1b', models.PositiveIntegerField()),
                ('b_2b', models.PositiveIntegerField()),
                ('b_3b', models.PositiveIntegerField()),
                ('b_hr', models.PositiveIntegerField()),
                ('b_rbi', models.PositiveIntegerField()),
                ('b_runs', models.PositiveIntegerField()),
                ('b_sb', models.PositiveIntegerField()),
                ('b_bb', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.Team')),
            ],
        ),
    ]
